# Generated by Django 3.1.7 on 2021-02-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Births',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, verbose_name='')),
                ('about', models.CharField(max_length=300, verbose_name='')),
                ('overview_text', models.CharField(max_length=100, verbose_name='')),
                ('specific_title', models.CharField(max_length=100, verbose_name='')),
                ('specific_link', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Deaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, verbose_name='')),
                ('about', models.CharField(max_length=300, verbose_name='')),
                ('overview_text', models.CharField(max_length=100, verbose_name='')),
                ('specific_title', models.CharField(max_length=100, verbose_name='')),
                ('specific_link', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, verbose_name='')),
                ('about', models.CharField(max_length=300, verbose_name='')),
                ('overview_text', models.CharField(max_length=100, verbose_name='')),
                ('specific_title', models.CharField(max_length=100, verbose_name='')),
                ('specific_link', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(verbose_name='')),
                ('bio', models.CharField(max_length=500, verbose_name='')),
            ],
        ),
    ]
